#Include winactive.ahk
#Include move.ahk
#Include edit.ahk
#Include find.ahk
#Include copypaste.ahk
#Include window.ahk
#Include bash.ahk
#Include vscode.ahk
#Include myprompt.ahk
#Include mydoc.ahk
#Include mycommand.ahk