#Include winactive.ahk
#Include move.ahk
#Include edit.ahk
#Include find.ahk
#Include copypaste.ahk
#Include window.ahk
#Include bash.ahk
#Include command.ahk
#Include doc.ahk
#Include vscode.ahk